Add --local
Signed-off-by: xplshn <xplshn@murena.io>

diff --git a/pelfCreator b/pelfCreator
--- a/pelfCreator
+++ b/pelfCreator
@@ -5,7 +5,7 @@ unset ARGV0 ARGS LD_PRELOAD LD_LIBRARY_PATH
 
 print_help() {
 	cat <<EOF
- Usage: $0 [|-m|-n|-p|-e|-r|-c|-z|-x|] <|-v|-h|>
+ Usage: $0 [|-m|-n|-p|-e|-r|-c|-z|-x|-o|] <|-v|-h|>
  
  Options:
    -m, --maintainer   Set the maintainer (required)
@@ -17,9 +17,12 @@ print_help() {
    -z, --dontpack     Disables .dwfs.AppBundle packaging, thus leaving only the AppDir
    -x, --norootfs     Ditches the rootfs and packs only the desired executables
    -o, --output-to    Set the output file name (optional, default: <name>-<date>.dwfs.AppBundle)
+   --local            A directory from which to pick up files such as 'LAUNCH', 'AppRun.rootfs', 'AppRun.sharun', 'rootfs.tgz', 'pelf-dwfs', 'bwrap', etc
    -v, --verbose      Enable verbose mode
    -h, --help         Display this help and exit
- 
+
+ ENV:
+     \$LOCAL_PATH       Same as the flag. Must point to a valid directory
  Examples:
    # With .desktop file (enabled integration with pelfd)
      $0 --maintainer animecowgirl79 --name mousepad --pkg-add mousepad --entrypoint org.xfce.mousepad.desktop
@@ -90,6 +93,10 @@ while true; do
 		OUTPUT_TO="$2"
 		shift 2
 		;;
+    --local)
+        LOCAL_PATH="$2"
+        shift 2
+        ;;
 	-v | --verbose)
 		VERBOSE=1
 		shift
@@ -109,6 +116,15 @@ while true; do
 		;;
 	esac
 done
+
+if [ -n "$LOCAL_PATH" ]; then
+    if [ -d "$LOCAL_PATH" ]; then
+        export PATH="$LOCAL_PATH:$PATH"
+    else
+        echo "Error: --local path must be a directory, it can contain AppRun, LAUNCH, bwrap, and pelf* tooling + mkdwarfs, rootfs.tgz, etc" >&2
+        exit 1
+    fi
+fi
 
 # Check for required arguments
 if [ -z "$MAINTAINER" ] || [ -z "$NAME" ] || [ -z "$PKG_ADD" ]; then
@@ -142,17 +158,25 @@ if ! wget -qO- "$ROOTFS_URL" | tar $TAR_OPTS - -C "$APPDIR/rootfs"; then
 	exit 1
 fi
 
-# Download and install bwrap
-if ! wget -qO "$APPDIR/usr/bin/bwrap" "https://bin.ajam.dev/$(uname -m)/bwrap-patched"; then
-	echo "Unable to install bwrap to $APPDIR/usr/bin/bwrap"
-	exit 1
+# Add bwrap
+if [ -f "$LOCAL_PATH/bwrap" ]; then
+    cp "$LOCAL_PATH/bwrap" "$APPDIR/usr/bin/bwrap"
+else
+    if ! wget -qO "$APPDIR/usr/bin/bwrap" "https://bin.ajam.dev/$(uname -m)/bwrap-patched"; then
+       	echo "Unable to install bwrap to $APPDIR/usr/bin/bwrap"
+       	exit 1
+    fi
 fi
 chmod +x "$APPDIR/usr/bin/bwrap"
 
-# Download AppRun
-if ! wget -qO "$APPDIR/AppRun" https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/assets/AppRun.rootfs-based; then
-	echo "Failed to download AppRun.rootfs-based"
-	exit 1
+# Add AppRun
+if [ -f "$LOCAL_PATH/AppRun" ]; then
+    cp "$LOCAL_PATH/AppRun.rootfs" "$APPDIR/AppRun"
+else
+    if ! wget -qO "$APPDIR/AppRun" https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/assets/AppRun.rootfs-based; then
+    	echo "Failed to download AppRun.rootfs-based"
+    	exit 1
+    fi
 fi
 chmod +x "$APPDIR/AppRun"
 
@@ -202,10 +226,14 @@ if [ "$MULTICALL" = "1" ]; then
 	echo "/usr/local/bin/LAUNCH" >"$APPDIR/rootfs/entrypoint"
 
 	mkdir -p "$APPDIR/rootfs/usr/local/bin"
-	# Download LAUNCH and set as entrypoint
-	if ! wget -qO "$APPDIR/rootfs/usr/local/bin/LAUNCH" "https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/assets/LAUNCH-multicall.rootfs.entrypoint"; then
-		echo "Failed to download LAUNCH for multicall"
-		exit 1
+	# Add LAUNCH (multicall helper for rootfs-based AppDirs)
+	if [ -f "$LOCAL_PATH/LAUNCH" ]; then
+	    cp "$LOCAL_PATH/LAUNCH" "$APPDIR/rootfs/usr/local/bin/LAUNCH"
+	else
+	    if ! wget -qO "$APPDIR/rootfs/usr/local/bin/LAUNCH" "https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/assets/LAUNCH-multicall.rootfs.entrypoint"; then
+	    	echo "Failed to download LAUNCH for multicall"
+	    	exit 1
+	    fi
 	fi
 	chmod +x "$APPDIR/rootfs/usr/local/bin/LAUNCH"
 
@@ -230,19 +258,27 @@ if [ "$NOROOTFS" = 1 ]; then
 	LD_LIBRARY_PATH="$APPDIR/rootfs/lib:$APPDIR/rootfs/usr/lib" lib4bin --dst-dir "$APPDIR" $TOBEKEPT && {
 		rm -rf "${APPDIR:?}/usr" "${APPDIR:?}/rootfs"
 		# Download LAUNCH and set as entrypoint
-		if ! wget -qO "$APPDIR/AppRun" "https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/assets/AppRun.sharun"; then
-			echo "Failed to download AppRun.sharun, unable to proceed with the NOROOTFS procedure"
-			exit 1
+		if [ -f "$LOCAL_PATH/AppRun.sharun" ]; then
+		    cp "$LOCAL_PATH/AppRun.sharun" "$APPDIR/AppRun"
+		else
+		    if ! wget -qO "$APPDIR/AppRun" "https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/assets/AppRun.sharun"; then
+		    	echo "Failed to download AppRun.sharun, unable to proceed with the NOROOTFS procedure"
+		    	exit 1
+		    fi
 		fi
 		chmod +x "$APPDIR/AppRun"
 	}
 fi
 
 echo "pelf-dwfs --add-appdir \"$APPDIR\" --appbundle-id \"$APPBUNDLE_ID\" --output-to \"$OUTPUT_TO\" --embed-static-tools --compression \"$COMPRESSION_OPTS\"" >"$APPDIR/.gen" && chmod +x "$APPDIR/.gen"
+# Final packaging
 if [ "$DONTPACK" != "1" ]; then
-	# Final packaging
-	if ! wget -qO- "https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/pelf-dwfs" | sh -s -- --add-appdir "$APPDIR" --appbundle-id "$APPBUNDLE_ID" --output-to "$OUTPUT_TO" --embed-static-tools --compression "$COMPRESSION_OPTS"; then
-		echo "Final packaging failed"
-		exit 1
+	if [ -f "$LOCAL_PATH/pelf-dwfs" ]; then
+		"$LOCAL_PATH/pelf-dwfs" --add-appdir "$APPDIR" --appbundle-id "$APPBUNDLE_ID" --output-to "$OUTPUT_TO" --embed-static-tools --compression "$COMPRESSION_OPTS"
+	else
+		if ! wget -qO- "https://raw.githubusercontent.com/xplshn/pelf/refs/heads/dev/pelf-dwfs" | sh -s -- --add-appdir "$APPDIR" --appbundle-id "$APPBUNDLE_ID" --output-to "$OUTPUT_TO" --embed-static-tools --compression "$COMPRESSION_OPTS"; then
+			echo "Final packaging failed"
+			exit 1
+		fi
 	fi
 fi
