Add Golang implementation of the runtime
Signed-off-by: xplshn <xplshn@murena.io>

diff --git a/pelf-dwfs b/pelf-dwfs
--- a/pelf-dwfs
+++ b/pelf-dwfs
@@ -1,11 +1,11 @@
 #!/bin/sh
 
 # Create a temporary directory for bundling the files
-_VAR_WORKDIR="/tmp/pelf_$(date '+%s%M%S')" # TODO: Only use this for the static tools and misc things
+_VAR_WORKDIR="/tmp/pelf_$(date '+%s%M%S')"
+_RUNTIME_FILE="$_VAR_WORKDIR/runtime"
 mkdir -p "$_VAR_WORKDIR" || exit 1
 # Trap all termination signals
 trap 'rm -rf "$_VAR_WORKDIR"' INT TERM HUP QUIT EXIT
-#
 
 # Exit with error message
 error() {
@@ -31,6 +31,7 @@ Options:
   --embed-static-tools                   Embed static tools into the bundle.
   --static-tools-dir=[directory]         Specify a custom directory from which to get the static tools.
   --retrieve-runtime=[filepath]          Output the runtime to a file and exit
+  --custom-runtime=[filepath]            Lets you specify which runtime shall be used
   --no-upx                               Disables usage of UPX compression in the static tools.
   --help                                 Display this help and exit.
 
@@ -55,7 +56,7 @@ check_and_process() {
 }
 
 # Parse command-line arguments using getopt
-if ! ARGS=$(getopt -o "" --long output-to:,compression:,add-appdir:,appbundle-id:,static-tools-dir:,retrieve-runtime:,embed-static-tools,no-upx,help -n "$0" -- "$@"); then
+if ! ARGS=$(getopt -o "" --long output-to:,compression:,add-appdir:,appbundle-id:,static-tools-dir:,retrieve-runtime:,custom-runtime:,embed-static-tools,no-upx,help -n "$0" -- "$@"); then
     print_help
     exit 1
 fi
@@ -101,6 +102,10 @@ while true; do
 		_VAR_RETRIEVE_RUNTIME="$2"
 		shift 2
 		;;
+	--custom-runtime)
+		_VAR_CUSTOM_RUNTIME="$2"
+		shift 2
+		;;
 	--no-upx)
 	    _VAR_NOUPX="1"
 	    shift
@@ -116,7 +121,6 @@ while true; do
 		;;
 	esac
 done
-
 
 # Check for required arguments after parsing
 if [ -z "$_VAR_RETRIEVE_RUNTIME" ]; then
@@ -198,11 +202,13 @@ else
 fi
 CONST_VERSION="2.0_dwfs_raw" # (vanilla)
 
-# Generate the loader script with conditional replacements
-LOADER_SCRIPT=$(
-	sed -e "s|__ENTRY_POINT__|${_VAR_APPBUNDLE_ID##*/}|g" \
-		-e "s|__PELF_VERSION__|${CONST_VERSION}|g" \
-		-e "s|__PELF_HOST__|${_VAR_HOST_INFO}|g" <<'_END_OF_LOADER_SCRIPT'
+if [ -n "$_VAR_CUSTOM_RUNTIME" ]; then
+	log "Using custom runtime: $_VAR_CUSTOM_RUNTIME"
+	cp "$_VAR_CUSTOM_RUNTIME" "$_RUNTIME_FILE" || error "Failed to copy custom runtime."
+else
+	log "Creating default runtime."
+	# Generate the default runtime script
+	cat >"$_RUNTIME_FILE" <<'_END_OF_LOADER_SCRIPT'
 #!/bin/sh
 # __APPBUNDLE__
 # This file was automatically generated by __PELF_VERSION__. Find out more about it here: https://github.com/xplshn/pelf
@@ -475,11 +481,12 @@ main "$@"
 
 exit $?
 _END_OF_LOADER_SCRIPT
-)
+fi
+
 
 # Create RUNTIME
 [ -z "$_VAR_RETRIEVE_RUNTIME" ] || {
-    echo "$LOADER_SCRIPT" >"$_VAR_RETRIEVE_RUNTIME"
+    cp "$_RUNTIME_FILE" "$_VAR_RETRIEVE_RUNTIME"
     log "Successfully wrote exported the runtime to \"$_VAR_RETRIEVE_RUNTIME\""
     log "   Notes:
         1. Add the marker for the static tools tgz prior to embedding the dwarfs archive. Remember to convert the tgz archive to base64 and only after adding the marker add the base64 static.tgz archive to this runtime
@@ -487,7 +494,19 @@ _END_OF_LOADER_SCRIPT
         3. Then mark as executable and you're good to go"
     exit 0
 } && {
-    echo "$LOADER_SCRIPT" >"$_VAR_OUT_FILE"
+	# Check if the runtime file contains __ENTRYPOINT__ (indicating it's a text file)
+	if grep -q "__ENTRYPOINT__" "$_RUNTIME_FILE"; then
+	    # The file is a normal text file, perform replacements directly
+	    sed -e "s|__ENTRY_POINT__|${_VAR_APPBUNDLE_ID##*/}|g" \
+	        -e "s|__PELF_VERSION__|${CONST_VERSION}|g" \
+	        -e "s|__PELF_HOST__|${_VAR_HOST_INFO}|g" \
+	        "$_RUNTIME_FILE" > "$_VAR_OUT_FILE"
+	else
+	    cp "$_RUNTIME_FILE" "$_VAR_OUT_FILE"
+		log "Injecting internal variables into binary runtime"
+	    printf "\n__ENTRY_POINT__: %s\n__PELF_VERSION__: %s\n__PELF_HOST__: %s\n" \
+	        "${_VAR_APPBUNDLE_ID##*/}" "${CONST_VERSION}" "${_VAR_HOST_INFO}" >> "$_VAR_OUT_FILE"
+	fi
 }
 
 embed_static_tools() {
