Make --local let you specify a rootfs in the LOCAL_PATH
Signed-off-by: xplshn <xplshn@murena.io>

diff --git a/pelfCreator b/pelfCreator
--- a/pelfCreator
+++ b/pelfCreator
@@ -153,9 +153,16 @@ echo "${0##*/} $ARGS" >"$APPDIR/.genSteps" && chmod +x "$APPDIR/.genSteps"
 
 # shellcheck disable=SC2086 # Double quote $TAR_OPTS to prevent globbing and word splitting.
 # Download and extract rootfs
-if ! wget -qO- "$ROOTFS_URL" | tar $TAR_OPTS - -C "$APPDIR/rootfs"; then
-	echo "Failed to download or extract rootfs"
-	exit 1
+if [ -f "$LOCAL_PATH/rootfs.tgz" ]; then
+	if ! tar $TAR_OPTS -C "$APPDIR/rootfs" -xf "$LOCAL_PATH/rootfs.tgz"; then
+		echo "Failed to extract local rootfs"
+		exit 1
+	fi
+else
+	if ! wget -qO- "$ROOTFS_URL" | tar $TAR_OPTS - -C "$APPDIR/rootfs"; then
+		echo "Failed to download or extract rootfs"
+		exit 1
+	fi
 fi
 
 # Add bwrap
